export function validateTxtFile(f) {
  if (!f) return { ok: false, error: "" };
  if (!/\.txt$/i.test(f.name))
    return { ok: false, error: "Only .txt files are supported" };
  if (f.size === 0)
    return { ok: false, error: "File is empty and cannot be processed" };
  return { ok: true };
}

export function validateEncryptedTxtFile(file) {
  if (!file) return { ok: false, error: "No file provided" };

  const name = file.name || "";
  // Require double extension: .enc.txt (case-insensitive)
  const isEncTxt = /\.enc\.txt$/i.test(name);

  if (!isEncTxt) {
    return {
      ok: false,
      error: "Only .enc.txt files generated by Encryptoid are supported",
    };
  }
  // size check (non-empty)
  if (typeof file.size === "number" && file.size <= 0) {
    return { ok: false, error: "Encrypted file appears to be empty" };
  }

  return { ok: true };
}
